/*
** Copyright 2005-2015  Solarflare Communications Inc.
**                      7505 Irvine Center Drive, Irvine, CA 92618, USA
** Copyright 2002-2005  Level 5 Networks Inc.
**
** This program is free software; you can redistribute it and/or modify it
** under the terms of version 2 of the GNU General Public License as
** published by the Free Software Foundation.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
*/



FTL_DECLARE(STRUCT_OO_PKTQ)
FTL_DECLARE(STRUCT_NS_MMAP_INFO)
FTL_DECLARE(UNION_EFAB_EVENT)
FTL_DECLARE(STRUCT_EF_EVENTQ_STATE)
FTL_DECLARE(STRUCT_CI_NI_DLLINK)
FTL_DECLARE(STRUCT_CI_NI_DLLIST)
FTL_DECLARE(STRUCT_PIO_BUDDY_ALLOCATOR)
FTL_DECLARE(STRUCT_OO_TIMESPEC)
FTL_DECLARE(STRUCT_NETIF_STATE_NIC)
FTL_DECLARE(STRUCT_CI_EPLOCK)
FTL_DECLARE(STRUCT_NETIF_CONFIG)
FTL_DECLARE(STRUCT_NS_RANGE)
FTL_DECLARE(STRUCT_NETIF_IPID_CB)
FTL_DECLARE(STRUCT_IP_TIMER_STATE)
FTL_DECLARE(STRUCT_IP_TIMER)
FTL_DECLARE(STRUCT_EF_VI_TXQ_STATE)
FTL_DECLARE(STRUCT_EF_VI_RXQ_STATE)
FTL_DECLARE(STRUCT_EF_VI_STATE)
FTL_DECLARE(STRUCT_NETIF_STATS)
#if CI_CFG_SUPPORT_STATS_COLLECTION
FTL_DECLARE(STRUCT_IPV4_STATS)
FTL_DECLARE(STRUCT_ICMP_STATS)
FTL_DECLARE(STRUCT_TCP_STATS)
FTL_DECLARE(STRUCT_UDP_STATS)
FTL_DECLARE(STRUCT_TCP_EXT_STATS)
FTL_DECLARE(STRUCT_IP_STATS)
#endif
FTL_DECLARE(STRUCT_NETIF_DBG_MAX)
FTL_DECLARE(STRUCT_NETIF_THRD_INFO)
FTL_DECLARE(STRUCT_EF_VI_STATS)
FTL_DECLARE(STRUCT_NETIF_STATE)
FTL_DECLARE(STRUCT_USER_PTR)
FTL_DECLARE(UNION_SLEEP_SEQ)
FTL_DECLARE(STRUCT_WAITABLE)
FTL_DECLARE(STRUCT_ETHER_HDR)
FTL_DECLARE(STRUCT_IP4_HDR)
FTL_DECLARE(STRUCT_IP4_PSEUDO_HDR)
FTL_DECLARE(STRUCT_CICP_VERINFO)
FTL_DECLARE(STRUCT_PMTU_STATE)
FTL_DECLARE(STRUCT_IP_HDRS)
FTL_DECLARE(STRUCT_TCP_HDR)
FTL_DECLARE(STRUCT_UDP_HDR)
FTL_DECLARE(STRUCT_TIMEVAL)
FTL_DECLARE(STRUCT_HDR_SPACE)
FTL_DECLARE(STRUCT_SOCK_OPTS)
FTL_DECLARE(STRUCT_ATOMIC)
FTL_DECLARE(STRUCT_SOCK_CPLANE)
FTL_DECLARE(STRUCT_SOCK)
FTL_DECLARE(STRUCT_IP_PKT_QUEUE)
FTL_DECLARE(STRUCT_UDP_SOCKET_STATS)
FTL_DECLARE(STRUCT_TCP_SOCKET_STATS)
FTL_DECLARE(STRUCT_UDP_RECV_Q)
FTL_DECLARE(STRUCT_TIMESTAMP_Q)
FTL_DECLARE(STRUCT_UDP)
FTL_DECLARE(STRUCT_IP_SOCK_STATS_COUNT)
FTL_DECLARE(STRUCT_IP_SOCK_STATS_RANGE)
FTL_DECLARE(STRUCT_IP_SOCK_STATS)
FTL_DECLARE(STRUCT_TCP_COMMON)
FTL_DECLARE(STRUCT_TCP)
FTL_DECLARE(STRUCT_TCP_SOCKET_LISTEN_STATS)
FTL_DECLARE(STRUCT_TCP_LISTEN)
FTL_DECLARE(STRUCT_WAITABLE_OBJ)
FTL_DECLARE(STRUCT_FILTER_TABLE_ENTRY)
FTL_DECLARE(STRUCT_FILTER_TABLE)
FTL_DECLARE(STRUCT_OO_PIPE_READ_PTR)
FTL_DECLARE(STRUCT_OO_PIPE_WRITE_PTR)
FTL_DECLARE(STRUCT_OO_PIPE_BUF_LIST_T)
FTL_DECLARE(STRUCT_OO_PIPE)
