obj-$(CONFIG_SFC_RESOURCE) := sfc_resource.o

sfc_resource-objs := resource_driver.o iopage.o \
	driverlink_new.o kernel_proc.o kfifo.o \
	nic.o eventq.o falcon.o falcon_mac.o \
	assert_valid.o buddy.o buffer_table.o \
	iobufset_resource.o resource_manager.o resources.o \
	vi_resource_alloc.o vi_resource_event.o vi_resource_flush.o \
	vi_resource_manager.o vi_allocator.o

