#!/bin/bash
######################################################################

me=$(basename "$0")
err()  { echo >&2 "$*"; }
log()  { err "$me: $*"; }
fail() { log "FAILED: $*"; exit 1; }
try()  { "$@" || fail "$*"; }

######################################################################
# main()

tgz="$1"
try [ -f "$tgz" ]
dir=${tgz%.tgz}
try tar xf "$tgz"
try [ -d "$dir" ]
try mv "$dir/ChangeLog" "$dir-ChangeLog.txt"
try mv "$dir/ReleaseNotes" "$dir-ReleaseNotes.txt"
try mv "$dir/README" "$dir-README.txt"
try rm -r "$dir"
