#!/bin/sh
# chkconfig: 35 50 50
# description: OpenOnload initialisation
### BEGIN INIT INFO
# Provides: openonload
# Required-Start: $network
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 
### END INIT INFO

case "$1" in
  start)
    /sbin/modprobe onload
    /sbin/onload_tool mknod sfc_char
    /sbin/onload_tool mknod onload
    /sbin/onload_tool mknod onload onload_epoll
    /sbin/modprobe sfc_affinity
    /sbin/onload_tool mknod sfc_affinity
    # sfc_affinity will overwrite your IRQ core affinitiy settings
    # so we do not do this by default.  It is however required if you wish
    # Onload to affinitise interrupts.
    # Uncomment this next line to spread the channels evenly over all cores
    # See "/usr/sbin/sfcaffinity_config --help" for more advanced usage.
    #/usr/sbin/sfcaffinity_config auto
    ;;
  *)
    ;;
esac
exit 0
